services:
  gemini-sandbox:
    build:
     context: .
     dockerfile: gemini-sdbx.Dockerfile
    image: gemini-sandbox
    container_name: gemini-sandbox
    volumes:
     - /Users/aakashmac/DevOps/Github/ollama/sandbox/:/workspace
    environment:
     GEMINI_API_KEY: ${GEMINI_API_KEY}
