services:
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    #restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      # ONLY mount the host's /proc directory
      - /proc:/host/proc:ro
      - ./textfile_collector:/host/custom_metrics:ro
    command:
          # Tell Node Exporter where the host /proc is
          - '--path.procfs=/host/proc'
          
          # OPTIONAL BUT RECOMMENDED: Turn off everything else to save resources
          - '--collector.disable-defaults'
          - '--collector.meminfo'   # Gets your RAM metrics
          - '--collector.cpu'       # Gets your CPU metrics
          - '--collector.loadavg'   # Gets system load averages
          - '--collector.stat'      # Gets basic system stats (boot time, etc.)
          - '--collector.textfile'
          - '--collector.textfile.directory=/host/custom_metrics'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    # restart: unless-required
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    # restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
