services:
  gemini-sandbox:
    build:
     context: .
     dockerfile: gemini-sdbx.Dockerfile
    image: gemini-sandbox
    container_name: gemini-sandbox
    volumes:
     - /Users/aakashmac/DevOps/Github/QuickSpin/:/workspace/QuickSpin
     - /Users/aakashmac/DevOps/Github/Terraform/:/workspace/Terraform
    environment:
     GEMINI_API_KEY: ${GEMINI_API_KEY}
     GEMINI_CLI_TRUST_WORKSPACE: "true"
