services:
  gemini-sandbox:
    build:
     context: .
     dockerfile: gemini-sdbx.Dockerfile
    image: gemini-sandbox
    container_name: gemini-sandbox
    volumes:
     - ${LOCAL_DIRECTORY_PATH}:/workspace
    environment:
     GEMINI_API_KEY: ${GEMINI_API_KEY}
     GEMINI_CLI_TRUST_WORKSPACE: "true"
