services:
  scrapper:
    image: ollama-scrapper:latest
    volumes:
      - /sys/class/thermal/thermal_zone0/temp:/sys/class/thermal/thermal_zone0/temp:ro
      - /home/ubuntu/ollama/LLM-Monitoring/textfile_collector/local-metrics.prom:/home/ubuntu/ollama/LLM-Monitoring/textfile_collector/local-metrics.prom:rw
      - /proc/meminfo:/proc/meminfo:ro
    resources:
      limits:
        memory: 120M
      reservations:
        memory: 80M
